[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

#Opciones que se ejecutan automaticamente.
addopts = -v --html=report.html --self-contained-html

# ✅ Personalización del reporte HTML
html_report_title = TalentoLab – Resumen de ejecución
html_report_description = Suite UI + API completa